---

- name: Run rc database
  docker_container:
    name: rc-database
    pull: yes
    image: postgres:11.1
    state: started
    recreate: "{{ DB_RECREATE }}"
    ports:
      - "{{ RC_DB_PORT }}:{{ DB_PORT }}"
    env:
      POSTGRES_USER: "{{ DB_USER }}"
      POSTGRES_PASSWORD: "{{ RC_DB_PWD }}"
      POSTGRES_DB: "{{ RC_DB_NAME }}"

- name: Launch RC app
  docker_container:
    name: rc-app
    pull: yes
    image: "slonepi/reference-collector:{{ RC_APP_VERSION }}"
    state: started
    recreate: yes
    ports:
      - "8092:8092"
    env:
      DATABASE_HOST: "rc-database"
      DATABASE_USER: "{{ DB_USER }}"
      DATABASE_PASSWORD: "{{ RC_DB_PWD }}"
      DATABASE_NAME: "{{ RC_DB_NAME }}"
      DATABASE_PORT: "{{ DB_PORT }}"
    links:
      - rc-database
