---

- name: Run rc database
  docker_container:
    name: rc-database
    pull: yes
    image: postgres:11.1
    state: started
    ports:
      - "{{ DB_PORT }}:{{ DB_PORT }}"
    env:
      POSTGRES_USER: "{{ DB_USER }}"
      POSTGRES_PASSWORD: "{{ DB_PWD }}"
      POSTGRES_DB: "{{ DB_NAME }}"

- name: Launch RC app
  docker_container:
    name: rc-app
    pull: yes
    image: slonepi/reference-collector:latest
    state: started
    restart: yes
    ports:
      - "8092:8092"
    env:
      DATABASE_HOST: "rc-database"
      DATABASE_USER: "{{ DB_USER }}"
      DATABASE_PASSWORD: "{{ DB_PWD }}"
      DATABASE_NAME: "{{ DB_NAME }}"
      DATABASE_PORT: "{{ DB_PORT }}"
    links:
      - rc-database


